dist: bionic
language: cpp

install:
  - pip install --user conan cmake

before_script:
  - mkdir build
  - cd build

matrix:
  include:
  #
  # G++ 
  #
  - os: linux
env:
      - TEST="G++"
    script:
      - cmake -DENABLE_TESTING=ON ..
      - make

  #
  # Clang 
  #
  - os: linux
    env:
      - TEST="Clang"
    script:
      - cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
      - make
      - make test

  #
  # Codecov
  #
  - os: linux
    env:
      - TEST="Codecov"
    script:
      - cmake -DENABLE_COVERAGE=ON -DENABLE_TESTING=ON ..
      - make
      - make test
      - cd ..
      - bash <(curl -s https://codecov.io/bash)

  #
  # Google Sanitizer
  #
  - os: linux
    env:
      - TEST="Google Sanitizer"
    script:
      - cmake -DENABLE_TESTING=ON -DENABLE_SANITIZER_ADDRESS:BOOL=TRUE -DENABLE_SANITIZER_LEAK:BOOL=TRUE -DENABLE_SANITIZER_MEMORY:BOOL=TRUE -DENABLE_SANITIZER_UNDEFINED_BEHAVIOR:BOOL=TRUE ..
      - make
      - make test
  #
  # Valgrind
  #
  - os: linux
    env:
      - TEST="Valgrind"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - valgrind
    script:
      - cmake ..
      - make
      - ctest -T memcheck
 
